export const projects = [
  {
    title: 'Monee',
    duration: '2025.03 - ',
    summary: 'PWA 기반 가계부 앱으로 캘린더, 통계, 수입/지출 분석 기능을 제공',
    tags: ['React', 'Redux', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    category: 'Web',
    github: 'https://github.com/nastorond/monee',
    notion: 'https://imaginary-editor-57f.notion.site/Monee-1ca842b2e8b18036b339e153f66ae425?source=copy_link',

    thumbnail: 'Monee.png',
    shortDesc: '가계부 프로젝트', 
  },
  // {
  //   title: 'Four Knights',
  //   duration: '2024.01 - 2024.02',
  //   summary: '사냥과 보스를 통해 재화를 얻고, 장비를 강화하며 성장하는 RPG게임',
  //   tags: ['Unity', 'C#'],
  //   category: 'Game',
  //   github: 'https://github.com/Siabel/Four_Knights',
  //   notion: 'https://www.notion.so/your-monee-docs',
  //   thumbnail: '/images/monee.png',
  //   shortDesc: '가계부 프로젝트', 
  // },
  {
    title: 'Algonion',
    duration: '2024.01 - 2024.02',
    summary: '알고리즘 학습을 위한 웹 플랫폼으로 문제 풀이 및 해설 제공',
    tags: ['React', 'TypeScript', 'SCSS'],
    category: 'Web',
    github: 'https://github.com/Siabel/algonion',
    notion: 'https://imaginary-editor-57f.notion.site/Algonion-6aa20dea7a7644998417a75cef492793?source=copy_link',
    thumbnail: 'Algonion.png',
    shortDesc: '알고리즘 학습 프로젝트', 
  },
  {
    title: 'Socrates',
    duration: '2023.11',
    summary: '사용자가 좋아하는 영화를 네거티브 필터링하여 추천해주는 사이트',
    tags: ['Python', 'Django', 'Vue'],
    category: 'Web',
    github: 'https://github.com/Siabel/Socrates',
    notion: 'https://imaginary-editor-57f.notion.site/Socrates-4a27e47028c44efabab916466a4fca59?source=copy_link',
    thumbnail: 'Socrates.png',
    shortDesc: '영화 추천 프로젝트', 
  },
]